"""db 2.0

Revision ID: 40a7518a2179
Revises: 
Create Date: 2024-11-17 15:55:04.053989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a7518a2179'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activities_id', table_name='activities')
    op.drop_index('ix_health_id', table_name='health')
    op.drop_index('ix_locations_id', table_name='locations')
    op.drop_index('ix_posts_id', table_name='posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    op.create_index('ix_locations_id', 'locations', ['id'], unique=False)
    op.create_index('ix_health_id', 'health', ['id'], unique=False)
    op.create_index('ix_activities_id', 'activities', ['id'], unique=False)
    # ### end Alembic commands ###
